package dev.alex.folderplayer;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;import android.util.AtomicFile;
import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;
public final class DocumentActivity extends Activity {
 private final ExecutorService worker=Executors.newSingleThreadExecutor();private final AtomicBoolean cancelled=new AtomicBoolean();private String source,initialSource,track,model;private List<String> original;private List<String> blocks,parts,notices;private boolean[] useBlock;private boolean busy,complete;private TextView status,output;private Button run,stop,review,all,save,copy,history;private JSONArray documents=new JSONArray();private boolean historyReadable=true;
 private TextView label(String s){TextView v=new TextView(this);v.setTextColor(Color.WHITE);v.setTextSize(17);v.setText(s);v.setPadding(0,12,0,12);v.setTextIsSelectable(true);return v;}
 private Button button(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setOnClickListener(l);return b;}
 @Override public void onCreate(Bundle state){super.onCreate(state);source=getIntent().getStringExtra("source");if(source==null)source="";initialSource=source;track=getIntent().getStringExtra("track");model=new TranslationClient(this).getModelId();original=DocumentTranslation.paragraphs(source);loadHistory();LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setBackgroundColor(Color.rgb(15,24,29));box.setPadding(24,24,24,24);if(Build.VERSION.SDK_INT>=30)box.setOnApplyWindowInsetsListener((v,i)->{android.graphics.Insets b=i.getInsets(WindowInsets.Type.systemBars());v.setPadding(24,b.top+16,24,b.bottom+16);return i;});ScrollView sc=new ScrollView(this);sc.addView(box);setContentView(sc);box.addView(label("Перевод полного текста"));status=label("По умолчанию результат собирается из предложений. Каждый абзац сравним с переводом блока; подозрительные места покажем отдельно.");box.addView(status);box.addView(label("Предупреждение не проверяет весь смысл. Переносы внутри предложения объединяются; куплеты разделяются пустой строкой. Перевод не привязан к времени LRC."));run=button("Перевести полный текст",v->translate());stop=button("Отмена",v->cancelled.set(true));review=button("Места с возможным пропуском",v->list(true));all=button("Все фрагменты",v->list(false));save=button("Сохранить полный результат",v->save());box.addView(run);box.addView(stop);box.addView(review);box.addView(all);box.addView(save);copy=button("Копировать текущий результат",v->copy(result()));box.addView(copy);history=button("История переводов ("+documents.length()+")",v->saved());box.addView(history);output=label("");box.addView(output);box.addView(button("Назад",v->finish()));active(false);}
 private void active(boolean b){busy=b;run.setEnabled(!b);stop.setEnabled(b);for(Button x:new Button[]{review,all,copy})x.setEnabled(!b&&complete);save.setEnabled(!b&&complete&&historyReadable);history.setEnabled(!b);}
 private void translate(){if(busy)return;if(source.trim().isEmpty()||source.length()>20000||source.split("\n",-1).length>500){status.setText("Нужен непустой текст до 20 000 символов и 500 строк");return;}complete=false;cancelled.set(false);active(true);output.setText("");worker.execute(()->{try{DocumentEngine engine=new DocumentEngine(this);model=engine.getModel();Map<String,String> cache=engine.translate(original,cancelled,(d,n)->ui(()->status.setText("Перевод: "+d+" / "+n)));List<String> b=new ArrayList<>(),p=new ArrayList<>(),w=new ArrayList<>();for(String src:original){String block=cache.get(CompletenessRules.block(src));List<String> translated=new ArrayList<>();for(String unit:CompletenessRules.units(src))translated.add(cache.get(unit));b.add(block);p.add(String.join("\n",translated));w.add(CompletenessRules.warning(block,translated,CompletenessRules.units(src)));}if(cancelled.get())throw new InterruptedException();ui(()->{if(cancelled.get()){status.setText("Перевод отменён");return;}blocks=b;parts=p;notices=w;useBlock=new boolean[b.size()];complete=true;refresh();});}catch(Exception e){ui(()->status.setText(cancelled.get()?"Перевод отменён. Результат не сохранён.":"Перевод не завершён: "+e.getMessage()));}finally{ui(()->active(false));}});}
 private String result(){List<String> selected=new ArrayList<>();for(int i=0;i<parts.size();i++)selected.add(useBlock[i]?blocks.get(i):parts.get(i));return DocumentTranslation.assemble(selected);}
 private void refresh(){output.setText(result());int n=0;for(String s:notices)if(!s.isEmpty())n++;status.setText("Готово. Мест с возможным пропуском: "+n+". Отсутствие предупреждений не доказывает полноту.");}
 private void list(boolean suspicious){if(busy||!complete)return;List<Integer> ids=new ArrayList<>();List<String> labels=new ArrayList<>();for(int i=0;i<original.size();i++)if(!original.get(i).trim().isEmpty()&&(!suspicious||!notices.get(i).isEmpty())){ids.add(i);labels.add("Фрагмент "+(i+1)+(useBlock[i]?" · блок":" · предложения"));}if(ids.isEmpty()){status.setText("Признаки крупного пропуска не найдены. Смысл и детали могут содержать ошибки.");return;}new AlertDialog.Builder(this).setTitle(suspicious?"Возможные пропуски":"Все фрагменты").setItems(labels.toArray(new String[0]),(d,n)->choose(ids.get(n))).setNegativeButton("Закрыть",null).show();}
 private void choose(int i){ScrollView sc=new ScrollView(this);sc.addView(label("Оригинал\n"+original.get(i)+"\n\nБлок\n"+blocks.get(i)+"\n\nПредложения\n"+parts.get(i)+"\n\n"+notices.get(i)));new AlertDialog.Builder(this).setTitle("Фрагмент "+(i+1)).setView(sc).setPositiveButton("Выбрать предложения",(d,n)->{useBlock[i]=false;refresh();}).setNeutralButton("Выбрать блок",(d,n)->{useBlock[i]=true;refresh();}).setNegativeButton("Закрыть",null).show();}
 private AtomicFile file(){return new AtomicFile(new File(getFilesDir(),"full-document-history.json"));}
 private String read(AtomicFile f)throws IOException{try(InputStream in=f.openRead()){ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] bytes=new byte[8192];int n;while((n=in.read(bytes))!=-1)out.write(bytes,0,n);return out.toString("UTF-8");}catch(FileNotFoundException e){return null;}}
 private void loadHistory(){try{String archive=read(file());String legacy=archive==null?read(new AtomicFile(new File(getFilesDir(),"full-document-last.json"))):null;documents=DocumentHistory.load(archive,legacy);}catch(Exception e){historyReadable=false;}}
 private void copy(String value){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("AFP перевод",value));Toast.makeText(this,"Перевод скопирован",Toast.LENGTH_SHORT).show();}
 private void save(){if(busy||!complete||!historyReadable)return;try{JSONObject row=new JSONObject().put("id",UUID.randomUUID().toString()).put("source",source).put("created",System.currentTimeMillis()).put("model",model).put("blocks",new JSONArray(blocks)).put("sentences",new JSONArray(parts)).put("warnings",new JSONArray(notices)).put("translation",result());JSONArray choices=new JSONArray();for(boolean b:useBlock)choices.put(b?"block":"sentences");row.put("choices",choices);JSONArray next=DocumentHistory.append(documents,row);AtomicFile f=file();FileOutputStream out=null;try{out=f.startWrite();out.write(DocumentHistory.serialize(next).getBytes(StandardCharsets.UTF_8));f.finishWrite(out);}catch(Exception e){if(out!=null)f.failWrite(out);throw e;}documents=next;history.setText("История переводов ("+documents.length()+")");if(track!=null && source.equals(initialSource)){try{new TranslationStore(this).save(track,source,result(),model);}catch(Exception e){status.setText("Перевод сохранён в истории, но экран песни не обновлён: "+e.getMessage());return;}}status.setText("Полный перевод добавлен в историю.");}catch(Exception e){status.setText("Не удалось сохранить: "+e.getMessage());}}
 private void saved(){if(busy)return;if(!historyReadable){status.setText("История повреждена или не читается. Сохранение заблокировано, прежние файлы оставлены.");return;}if(documents.length()==0){status.setText("Сохранённых переводов пока нет");return;}String[] labels=new String[documents.length()];for(int i=0;i<labels.length;i++){JSONObject row=documents.optJSONObject(labels.length-1-i);String preview=row.optString("source").replace('\n',' ');if(preview.length()>80)preview=preview.substring(0,80)+"…";labels[i]=android.text.format.DateFormat.format("dd.MM HH:mm",row.optLong("created"))+" · "+preview;}new AlertDialog.Builder(this).setTitle("История полных переводов").setItems(labels,(d,i)->showSaved(documents.optJSONObject(documents.length()-1-i))).setNegativeButton("Закрыть",null).show();}
 private void showSaved(JSONObject row){ScrollView sc=new ScrollView(this);sc.addView(label("Оригинал\n"+row.optString("source")+"\n\nСохранённый перевод\n"+row.optString("translation")));new AlertDialog.Builder(this).setTitle("Сохранённый перевод").setView(sc).setPositiveButton("Копировать",(d,x)->copy(row.optString("translation"))).setNeutralButton("Открыть для сравнения",(d,x)->restore(row)).setNegativeButton("Закрыть",null).show();}
 private void restore(JSONObject row){try{source=row.getString("source");model=row.getString("model");original=DocumentTranslation.paragraphs(source);blocks=strings(row.getJSONArray("blocks"));parts=strings(row.getJSONArray("sentences"));notices=strings(row.getJSONArray("warnings"));useBlock=new boolean[blocks.size()];JSONArray choices=row.getJSONArray("choices");for(int i=0;i<useBlock.length;i++)useBlock[i]=choices.getString(i).equals("block");if(original.size()!=blocks.size())throw new JSONException("Части не совпадают");complete=true;refresh();active(false);}catch(Exception e){complete=false;active(false);status.setText("Не удалось открыть сохранение: "+e.getMessage());}}
 private List<String> strings(JSONArray a)throws JSONException{List<String> out=new ArrayList<>();for(int i=0;i<a.length();i++)out.add(a.getString(i));return out;}
 private void ui(Runnable r){runOnUiThread(()->{if(!isDestroyed())r.run();});}
 @Override protected void onDestroy(){cancelled.set(true);worker.shutdownNow();super.onDestroy();}
}
